services:
  postgres:
    image: postgres:15
    container_name: transit-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: transit_wallet
    ports:
      - "5432:5432"
    networks:
      - transit-wallet-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  transit-wallet-net:
    driver: bridge
